### ISSUE TITLE
Add support for docker-in-docker configuration

### ISSUE THREAD

**Issue by brendanstennett** [hyperhq/hykins#16]
Running commands inside a container is great and works for a lot of setups but it would be great if we could specify a repo with a docker-compose.yml file, and perform a docker-compose run to execute tests.

**Comment by rebyn** [comment]
You can tweak your [slave container](https://github.com/hyperhq/hykins-docs) to install the Hyper CLI and upon builds, fetch `docker-compose.yml` and use `hyper compose` ([ref](https://docs.hyper.sh/GettingStarted/part_3.html)) to pull up your entire suite. This is what I have been doing to perform one off CI runs with Hyper.

A (very) rough flow:

```
curl COMPOSE_LINK > docker-compose.yml
hyper compose pull
hyper compose up -d
hyper logs -f app_test_1
hyper compose stop
hyper compose rm
````

**Comment by Gnep** [comment]
Here is a prebaked DinH image: https://hub.docker.com/r/hyperhq/docker-in-hyper/

**Comment by brendanstennett** [comment]
@Gnep Interesting.  This could be the ticket.  I am however getting a container start error on jenkins with that image:
```
Start time: 2017-08-31 13:34:31 UTC
FATAL: java.io.IOException: Launch container timeout
java.io.IOException: Launch container timeout
	at sh.hyper.hyperslaves.HyperComputerLauncher.launch(HyperComputerLauncher.java:82)
	at sh.hyper.hyperslaves.HyperComputerLauncher.launch(HyperComputerLauncher.java:58)
	at it.dockins.dockerslaves.api.OneShotSlave.provision(OneShotSlave.java:123)
Caused: it.dockins.dockerslaves.api.OneShotExecutorProvisioningException
	at it.dockins.dockerslaves.api.OneShotSlave.provisionFailed(OneShotSlave.java:145)
	at it.dockins.dockerslaves.api.OneShotSlave.provision(OneShotSlave.java:129)
	at it.dockins.dockerslaves.api.OneShotSlave.createLauncher(OneShotSlave.java:154)
	at sh.hyper.hyperslaves.HyperSlave.createLauncher(HyperSlave.java:82)
	at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:517)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:448)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE
```

I'll keep investigating further but wondering if you may have come across this. 

#### Project configuration
Docker Image: hyperhq/docker-in-hyper
Container Size: S4
Build - Execute Shell:
```
docker ps
docker run --name hello ubuntu:14.04 echo "Hello World"
docker rm hello
```

**Comment by Jimmy-Xu** [comment]
@brendanstennett
Jenkins Slave image should contain java. 
You can use this image `hyperhq/docker-in-hyper:slave_centos7` ([Dockerfile](https://github.com/hyperhq/jenkins-image-slave/blob/master/jenkins-slave-docker-in-hyper/centos/7/Dockerfile))

**hyperhq/docker-in-hyper:slave_centos7** = `hyperhq/docker-in-hyper:centos7` + `jenkinsci/slave:latest`

Docker Image: `hyperhq/docker-in-hyper:slave_centos7`
Container Size: S4
Build - Execute Shell:
```
screen -S docker -d -m "/root/run-docker.sh"
sleep 2

docker ps
docker run --name hello ubuntu:14.04 echo "Hello World"
docker rm hello
```

Output:
```
Started by user admin
Start time: 2017-08-31 17:09:47 UTC
$ /var/jenkins_home/bin/hyper --config /var/jenkins_home/.hyper inspect -f '{{.Id}}' hyperhq/docker-in-hyper:slave_centos7
'sha256:62cb4459a5b29d2a507855b1a03d9d8fc50e53592be9ff8192c91b243323aaf9'
Done setting up at: 2017-08-31 17:10:10 UTC
Done in 22 seconds
Building remotely on Container for test-docker-in-hyper#8 in workspace /home/jenkins/workspace/test-docker-in-hyper
+ cd /home/jenkins/workspace/test-docker-in-hyper
+ chmod +x /tmp/hudson6936561854553313292.sh
+ /tmp/hudson6936561854553313292.sh
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
Unable to find image 'ubuntu:14.04' locally
Trying to pull repository docker.io/library/ubuntu ... 
sha256:6a3e01207b899a347115f3859cf8a6031fdbebb6ffedea6c2097be40a298c85d: Pulling from docker.io/library/ubuntu
48f0413f904d: Pulling fs layer
2bd2b2e92c5f: Pulling fs layer
06ed1e3efabb: Pulling fs layer
a220dbf88993: Pulling fs layer
57c164185602: Pulling fs layer
a220dbf88993: Waiting
57c164185602: Waiting
2bd2b2e92c5f: Verifying Checksum
2bd2b2e92c5f: Download complete
06ed1e3efabb: Verifying Checksum
06ed1e3efabb: Download complete
57c164185602: Verifying Checksum
57c164185602: Download complete
a220dbf88993: Verifying Checksum
a220dbf88993: Download complete
48f0413f904d: Verifying Checksum
48f0413f904d: Download complete
48f0413f904d: Pull complete
2bd2b2e92c5f: Pull complete
06ed1e3efabb: Pull complete
a220dbf88993: Pull complete
57c164185602: Pull complete
Digest: sha256:6a3e01207b899a347115f3859cf8a6031fdbebb6ffedea6c2097be40a298c85d
Status: Downloaded newer image for docker.io/ubuntu:14.04
Hello World
hello
Finished: SUCCESS
```
